### ISSUE TITLE
Simulation while animation

### ISSUE THREAD

**Issue by mkowalik** [mkowalik/2DRobotSimulator#6]

**Comment by mkowalik** [comment]
One manager.queue() for all the robots. Synchronisation.

**Comment by pkruk** [comment]
@mkowalik  awesome, looks very good, but still not perfect. Test the case when two robots have a collisions:
One robot after few steps, stops immediately, when second i still moving. 
How to reproduce:
uncomment code in UserRobot2, and run simulation again.

**Comment by mkowalik** [comment]
@pkruk For me this situation works ok. Please, push on a new branch crashing code ;-)

**Comment by pkruk** [comment]
ok is working at now
